import type { Metadata } from 'next'
import './globals.css'
import React, { PropsWithChildren } from 'react'
import { sans } from '@/assets/fonts'
import Header from '@/components/header'

export const metadata: Metadata = {
  title: 'Cardápio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-br" className={`${sans.variable} h-full`}>
      <body className="bg-[#FAFAFA] h-full grid grid-rows-[auto_1fr_auto]">
        <Header />
        <div className="overflow-auto py-5">{children}</div>
      </body>
    </html>
  )
}
