import type { Metadata } from 'next'
import './globals.css'
import React, { PropsWithChildren } from 'react'
import Header from '@/components/header'
import { Outfit as FontFamily } from 'next/font/google'

const sans = FontFamily({
  variable: '--font-sans',
  weight: ['400', '500', '700'],
  adjustFontFallback: true,
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    template: '%s | Cardápio',
    default: 'Cardápio',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-br" className={`${sans.variable} h-full`}>
      <body className="h-full grid grid-rows-[auto_1fr_auto]">
        <Header />
        <div className="overflow-auto">{children}</div>
        <div id="action-bar"></div>
      </body>
    </html>
  )
}
