import type { Metadata } from 'next'
import './globals.css'
import React, { PropsWithChildren } from 'react'
import { sans } from '@/app/assets/fonts'
import Header from '@/components/header'
import { ActionBarRoot } from '@/components/action-bar-root'

export const metadata: Metadata = {
  title: 'Cardápio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="pt-br" className={`${sans.variable} h-full`}>
      <body className="bg-slate-100 h-full grid grid-rows-[auto_1fr_auto]">
        <Header />
        <div className="overflow-auto">{children}</div>
        <ActionBarRoot />
      </body>
    </html>
  )
}
